export const PERMISSIONS = [
  { id: 1, title_en: "Home Access", title_ar: "الوصول للصفحة الرئيسية" },
  { id: 2, title_en: "View Categories", title_ar: "عرض الفئات" },
  { id: 3, title_en: "Manage Categories", title_ar: "إدارة الفئات" },
  { id: 4, title_en: "View Units", title_ar: "عرض الوحدات" },
  { id: 5, title_en: "Manage Units", title_ar: "إدارة الوحدات" },
  { id: 6, title_en: "View Product Catalog", title_ar: "عرض كتالوج المنتجات" },
  { id: 7, title_en: "Manage Product Catalog", title_ar: "إدارة كتالوج المنتجات" },
  { id: 8, title_en: "View Purchase Requests", title_ar: "عرض طلبات الشراء" },
  { id: 9, title_en: "Manage Purchase Requests", title_ar: "إدارة طلبات الشراء" },
  { id: 10, title_en: "View RFQs", title_ar: "عرض طلبات الأسعار" },
  { id: 11, title_en: "Manage RFQs", title_ar: "إدارة طلبات الأسعار" },
  { id: 12, title_en: "View Suppliers", title_ar: "عرض الموردين" },
  { id: 13, title_en: "Manage Suppliers", title_ar: "إدارة الموردين" },
  { id: 14, title_en: "View Customers", title_ar: "عرض العملاء" },
  { id: 15, title_en: "Manage Customers", title_ar: "إدارة العملاء" },
  { id: 16, title_en: "View Settings", title_ar: "عرض الإعدادات" },
  { id: 17, title_en: "Manage Settings", title_ar: "تعديل الإعدادات" },
  { id: 18, title_en: "View Notifications", title_ar: "عرض الإشعارات" },
  { id: 19, title_en: "Manage Notifications", title_ar: "إدارة الإشعارات" },
  { id: 20, title_en: "View Roles & Permissions", title_ar: "عرض الأدوار والصلاحيات" },
  { id: 21, title_en: "Manage Roles & Permissions", title_ar: "إدارة الأدوار والصلاحيات" },
];
