export const quotationsData = [
  {
    key: 1,
    reference: "PO/02418",
    vendor: "EST Amry Castle Commercial",
    project: "S.B Survey TS-84",
    purchase_representation: "Tayam",
    order_deadline: "11 days ago",
    total: "1,405 SR",
    status: "Waiting PM Approval",
    invoiced: false,
  },
  {
    key: 2,
    reference: "PO/02419",
    vendor: "EST Amry Castle Commercial",
    project: "S.B Survey TS-84",
    purchase_representation: "Tayam",
    order_deadline: "11 days ago",
    total: "1,405 SR",
    status: "RFQ",
    invoiced: false,
  },
  {
    key: 3,
    reference: "PO/02420",
    vendor: "EST Amry Castle Commercial",
    project: "S.B Survey TS-84",
    purchase_representation: "Tayam",
    order_deadline: "11 days ago",
    total: "1,405 SR",
    status: "Waiting PM Approval",
    invoiced: true,
  },
  {
    key: 4,
    reference: "PO/02421",
    vendor: "EST Amry Castle Commercial",
    project: "S.B Survey TS-84",
    purchase_representation: "Tayam",
    order_deadline: "11 days ago",
    total: "1,405 SR",
    status: "RFQ",
    invoiced: false,
  },
];
